### ISSUE TITLE
[references] clarify status of IQ Semantic Web special issue which can be referenced in the spec

### ISSUE THREAD

**Issue by boschthomas** [linked-statistics/disco-spec#117]

**Comment by boschthomas** [comment]
E.2: all publications and presentations related to disco

**Comment by wlthomas** [comment]
http://iassistdata.org/deprecated/iq/issue/38/4
IASSIST Quarterly (38: Winter)

Semantic Web Applications for the Social Sciences 
Thomas BoschBenjamin Zapilko
pg:  7 
Full Text (PDF):  
application/pdf iconiqvol38_4_39_1_boschzapilko.pdf

DDI-RDF Discovery – A Discovery Model for Microdata 
Thomas BoschOlof OlssonBenjamin ZapilkoArofan GregoryJoachim Wackerow
pg:  17 
Full Text (PDF):  
application/pdf iconiqvol38_4_39_1_bosch_.pdf

Use Cases Related to an Ontology of the Data Documentation Initiative 
Thomas BoschBrigitte Mathiak
pg:  25 
Full Text (PDF):  
application/pdf iconiqvol38_4_39_1_boschmathiak.pdf

Linking Study Descriptions to the Linked Open Data Cloud 
Johann SchaibleBenjamin ZapilkoThomas BoschWolfgang Zenk-Möltgen
pg:  38 
Full Text (PDF):  
application/pdf iconiqvol38_4_39_1_schaible.pdf

**Comment by boschthomas** [comment]
see issue #219
