### ISSUE TITLE
Main possible improvements [Achim, Ben]

### ISSUE THREAD

**Issue by boschthomas** [linked-statistics/disco-spec#155]
## Benedikt Kämpgen (26.06.) [discussed]

1) Clarifying required background information about DDI and ensuring
that terms used in the text have been introduced.

2) Having complete examples, e.g., including a physical data file such
as a CSV. Clarifying the relationship between figures, text and turtle
samples.

3) One great benefit of Disco I see in the summary statistics. I am not
sure, though, whether the provided information will help publishers to
create such information.

4) The relationship of disco to the entire ddi landscape is unclear.
Instead of the full "11. DDI-XML Bidirectional Mappings", a more
comprehensive definition may be more helpful.

**Comment by JoachimWackerow** [comment]
Suggested wording in the first paragraph of "11. DDI-XML Bidirectional Mappings":
The main intention of Disco is to provide a RDF representation of DDI resources for discovery purposes in the Linked Data web. Nevertheless, bidirectional mappings between disco and DDI Lifecycle (DDI-L) are provided.

**Comment by JoachimWackerow** [comment]
Changed accordingly
