### ISSUE TITLE
links to definition of terms of the domain

### ISSUE THREAD

**Issue by boschthomas** [linked-statistics/disco-spec#181]
- descriptive statistics
- summary statistics
- category statistics
- coverage
- valid / invalid
- weighted
- universe
- representation of variables

**Comment by JoachimWackerow** [comment]
Possibly a link per term to an acknowledged glossary.

**Comment by JoachimWackerow** [comment]
From OECD glossary:
* descriptive statistics: https://stats.oecd.org/glossary/detail.asp?ID=3632, https://en.wikipedia.org/wiki/Descriptive_statistics
* summary statistics
* category statistics
* valid / invalid
* weighted
* universe, https://stats.oecd.org/glossary/detail.asp?ID=2087
* representation of variables: https://stats.oecd.org/glossary/detail.asp?ID=2304

Coverage
from: SDMX Glossary Version 2.0, October 2018 (https://sdmx.org/)
Definition of the scope of the data compiled.
Context	This metadata element is used to describe the key dimensions delimiting the statistics produced, e.g. geographical, products, economic and other sectors, industry, occupation, transactions, etc., as well as relevant exceptions and exclusions. It can also specify the period of time for which data are provided.
	The term "Coverage" describes the scope of the data compiled, rather than the characteristics of the survey.

**Comment by JoachimWackerow** [comment]
Suggested explanations and references see: [glossary.txt](https://github.com/linked-statistics/disco-spec/files/2931416/glossary.txt)

This issue is related to #233 where missing descriptions and link anchors are described for 
LogicalDataSet
inputvariable
representation
representedvariable
variablequantity
weightedby

**Comment by JoachimWackerow** [comment]
re glossary.txt
keep "Category statistics". It is a term and element in DDI 3.2. Even it is a little misleading, it will be kept.
See: http://www.ddialliance.org/Specification/DDI-Lifecycle/3.2/XMLSchema/FieldLevelDocumentation/schemas/physicalinstance_xsd/elements/CategoryStatistic.html
Adapted text:
Category Statistics
The value of a statistic associated with a category value (even it can be applied to numeric values of metric variables). A frequency is the number of times a data value occurs. [https://www.statisticshowto.datasciencecentral.com/how-to-make-a-frequency-chart-and-determine-frequency/]
Frequency counts (absolute) and percentages (relative) of the values of individual variables. See also https://en.wikipedia.org/wiki/Frequency_(statistics)

**Comment by JoachimWackerow** [comment]
All terms have now a general description when they occur the first time. Some have a link to an acknowledged website for further explanation.
