### ISSUE TITLE
create diagrams

### ISSUE THREAD

**Issue by boschthomas** [linked-statistics/disco-spec#201]
- object-properties.svg [Achim]
- object-properties_HiRes_vertical.png [Achim]

**Comment by BenZapilko** [comment]
Ben will double check this issue whether changes are have to be done.

**Comment by BenZapilko** [comment]
This issue seems to be solved according to #110 and Fig. 29, 30, and 31.

**Comment by boschthomas** [comment]
Hi  @BenZapilko Hi @JoachimWackerow 

really happy joining again :)

I guess, this is the Enterprise Architect project file you are searching for:
https://github.com/linked-statistics/disco-spec/blob/master/diagrams/DDI-RDFDiscoveryVocabulary.eap

**Comment by JoachimWackerow** [comment]
Combined uml diagram, object-properties, updated.
High resolution vertical created, object-properties_HiRes_vertical.png. This is for printing.
SVG created. viewBox attribute removed, width set to 461mm, height to 277mm.
It works with zoom in browsers Opera, Chrome, Internet Explorer (best), Firefox.
