### ISSUE TITLE
reference implementations

### ISSUE THREAD

**Issue by boschthomas** [linked-statistics/disco-spec#216]
- Missy [Thomas added sub-chapter to chapter 12 'reference implementations' in html spec]
- DwB [contact Pascal and/or Ørnulf]
- SND [contact Olof]
- Danish National Archives [contact Jannik]
- sparql endpoints [#217]
- models
- textual description

**Comment by JoachimWackerow** [comment]
double check and provide links for MISSY, Insee, and SND

**Comment by JoachimWackerow** [comment]
MISSY: https://www.gesis.org/missy/
SND and Insee asked

**Comment by JoachimWackerow** [comment]
Neither SND or Insee have currently real implementations.

The section on MISSY is already in the spec.
