### ISSUE TITLE
set up publicly available sparql endpoint for Missy 

### ISSUE THREAD

**Issue by boschthomas** [linked-statistics/disco-spec#217]
- Achim speaks to Jeanette
- technical set up [Ben]

**Comment by JoachimWackerow** [comment]
There seems to be no real issue with this. We are waiting on approval of the leadership.
How fast can it be set up technically?

**Comment by BenZapilko** [comment]
The SPARQL endpoint is already available. We just need to import the data and need to define a nice address that is accessible externally.

**Comment by mazlo** [comment]
If I may comment on this: we are currently checking which data we may put into the endpoint, which will be publicly available of course, because the Missy database might contain some sensible statistics data. As @JoachimWackerow said, we are waiting for approval.

**Comment by BenZapilko** [comment]
Does not relate to the finalization of Disco.
