### ISSUE TITLE
Vocabulary references dcterms:Dataset, should be dcmitype:Dataset

### ISSUE THREAD

**Issue by gkellogg** [linked-statistics/disco-spec#220]
Looking at http://dublincore.org/documents/dcmi-terms/ it's clear that `Dataset` is defined in the DCMI Type Vocabulary, not dcterms, which is born out in the actual vocabulary definitions. The discovery.ttl file should be updated accordingly.

This affects `disco:DataFile` which should be a subClass of `dcmitype:Dataset`.

**Comment by duffgui** [comment]
You're the correct prefix is dcmitype and should be corrected in both the turtle serialisation and the HTML specification. However, I don't think dcmitype:Dataset is that much used compared to void:Dataset (https://www.w3.org/TR/void/#dataset) for instance.
There is also a discrepancy between the Turtle file and the HTML draft : the ttl file defines explicitly disco:DataSet as a sub-class of dcmitype:Dataset whereas the HTML draft only mentions it in a comment.

**Comment by BenZapilko** [comment]
- change the model
- change the text in the html specification
- change the diagrams

**Comment by JoachimWackerow** [comment]
changes made accordingly to:
figure 19, data-file-coverage
figure 20, overview-data-set
figure 22, data-file
figure 23, descriptive-statistics
