### ISSUE TITLE
disco:responseDomain references undefined class disco:Representation

### ISSUE THREAD

**Issue by gkellogg** [linked-statistics/disco-spec#221]

**Comment by boschthomas** [comment]
added disco:Representation to turtle file and validated the turtle file:

disco:Representation 
    a rdfs:Class, owl:Class;
    rdfs:subClassOf [ a owl:Class; owl:unionOf (rdfs:Datatype skos:ConceptScheme skos:OrderedCollection)];
    rdfs:label "Representation of a variable, question, or variable definition."@en;
    rdfs:comment "Representation of a variable, question, or variable definition."@en;
    rdfs:isDefinedBy <http://rdf-vocabulary.ddialliance.org/discovery>.
