### ISSUE TITLE
Code and Categories [7.3]

### ISSUE THREAD

**Issue by duffgui** [linked-statistics/disco-spec#222]
It is convenient and good practice in RDF when developing a code list to also create a Class to denote all the codes within the code list, irrespective of hierarchical structure. Here is below a rewriting of the example 24 by using the common convention that the class name is the same as that of the concept scheme but with leading upper case.

ddi:sexRepr a skos:ConceptScheme, disco:Representation;
  skos:hasTopConcept ddi:SexM, ddi:SexF.

ddi:SexM a skos:Concept;
  skos:notation "1";
  skos:prefLabel "Male"@en, "Homme"@fr;
  skos:inScheme ddi:SexRepr.

ddi:SexF a skos:Concept;
  skos:notation "2";
  skos:prefLabel "Female"@en, "Femme"@fr;
  skos:inScheme ddi:SexRepr.

ddi:SexRepr a rdfs:Class, owl:Class;
    rdfs:subClassOf skos:Concept ;
    rdfs:label "Code list for Sex (SEX) - codelist class"@en;
    rdfs:comment "This  code list provides the gender."@en;
    rdfs:seeAlso ddi:sexRepr .

**Comment by BenZapilko** [comment]
Updated Example 24 by merging rdfs:label and rdfs:comment to the Concept Scheme ddi:sexRepr
