### ISSUE TITLE
prov:hadRole [4.2]

### ISSUE THREAD

**Issue by duffgui** [linked-statistics/disco-spec#223]
Here is the specification of prov:hadRole in PROV-O:https://www.w3.org/TR/prov-o/#hadRole
The domain is not a foaf:Agent which has no relationship (if didn't miss anything in PROV-O) to any of prov:Association or prov:InstantaneousEvent or prov:Influence.
The range is not a skos:Concept, but a prov:Role which is not related to any skos class.

**Comment by BenZapilko** [comment]
Easiest solutio would be another property as a relation between foaf:Agent and skos:Concept.

Best solution would be to model it correctly towards PROV-O.

**Comment by BenZapilko** [comment]
Changed prov:hadRole to disco:hadRole in the specification and turtle, nt, rdf, xml files.

Still open:
- change prov:hadRole to disco:hadRole in Figure 11.

**Comment by JoachimWackerow** [comment]
figure 11, study-agent, changed accordingly.
