### ISSUE TITLE
Revise editor and author information

### ISSUE THREAD

**Issue by boschthomas** [linked-statistics/disco-spec#231]
@BenZapilko @JoachimWackerow 

could you please change the editor and author information? ;-)

As is: Thomas Bosch , GESIS

Current: Thomas Hartmann (http://www.dr-thomashartmann.de/),  Robert Bosch GmbH (https://www.bosch.com/)

Thx

**Comment by BenZapilko** [comment]
I changed the name and URL. I didn't change the affiliation, since it is relevant which affiliation it was while you were working on Disco, not where you work now.

**Comment by BenZapilko** [comment]
Why are changes not visible at http://rdf-vocabulary.ddialliance.org/discovery.html ?
